import type { SiteContent } from "./types"

export const DEFAULT_CONTENT: SiteContent = {
  hero: {
    headline: "Trouvez le bien qui vous correspond, sans perdre de temps.",
    subheadline: "Je suis Chabane Chawki, agent immobilier à Oran. J'utilise le marketing et la vidéo pour attirer des acheteurs sérieux et vous faire gagner un temps précieux.",
    badge: "Oran, Algérie — Immobilier Premium",
    backgroundImage: "",
    stat1Value: "100+", stat1Label: "Biens vendus",
    stat2Value: "48h", stat2Label: "Délai moyen de contact",
    stat3Value: "Oran", stat3Label: "Expert local",
    ctaPrimaryText: "Me contacter sur WhatsApp",
    ctaSecondaryText: "Voir les biens disponibles",
  },
  about: {
    headline: "Je ne suis pas un agent immobilier classique.",
    subheadline: "Je suis un vendeur de biens.",
    paragraph1: "Je m'appelle Chabane Chawki, fondateur de Chabano Properties. J'ai choisi de construire ma marque différemment : là où les agences traditionnelles font de la pub générique, moi je crée du contenu vidéo qui met en valeur chaque bien.",
    paragraph2: "Mon objectif est simple : vous faire gagner du temps, vous éviter les visites inutiles, et vous connecter avec les bonnes personnes.",
    yearsExperience: "5+",
    experienceLabel: "ans dans l'immobilier à Oran",
    profileImage: "",
  },
  services: {
    sectionLabel: "Ce que je fais",
    sectionTitle: "Un accompagnement sur mesure,",
    sectionSubtitle: "Acheteur, vendeur, investisseur, promoteur — chaque profil mérite une approche différente.",
    service1: { tag: "Achat", title: "Vous cherchez à acheter ?", desc: "F2, F3, F4 — peu importe votre budget, je connais les bons biens avant même qu'ils soient publiés.", benefit1: "Sélection personnalisée", benefit2: "Visites vidéo avant déplacement", benefit3: "Accompagnement jusqu'à la signature", cta: "Je cherche un appartement" },
    service2: { tag: "Vente", title: "Vous vendez votre bien ?", desc: "Je crée une vidéo professionnelle et j'attire des clients sérieux en quelques jours.", benefit1: "Vidéo professionnelle", benefit2: "Diffusion sur mes réseaux", benefit3: "Acheteurs sérieux uniquement", cta: "Vendre mon bien" },
    service3: { tag: "Investissement", title: "Vous investissez ?", desc: "Oran est en pleine mutation. Je vous guide sur les zones à fort potentiel.", benefit1: "Analyse des quartiers porteurs", benefit2: "Opportunités off-market", benefit3: "Conseil rentabilité locative", cta: "Découvrir les opportunités" },
    service4: { tag: "Promotion", title: "Commercialisation de promotions ?", desc: "Vous êtes promoteur immobilier ? Je commercialise vos projets résidentiels à Oran avec une stratégie marketing digitale complète.", benefit1: "Stratégie marketing digitale", benefit2: "Présentation vidéo du projet", benefit3: "Base d'acheteurs qualifiés", cta: "Commercialiser mon projet" },
  },
  video: {
    sectionLabel: "Mon avantage",
    headline: "Vos biens, présentés comme des propriétés de prestige",
    paragraph1: "La plupart des agents postent quelques photos floues et attendent. Moi, je fais des vidéos qui montrent chaque bien sous son meilleur angle.",
    paragraph2: "Résultat : les acheteurs arrivent déjà convaincus. Les visites sont plus courtes, les décisions plus rapides.",
    videoThumbnail: "", stat1Value: "3x", stat1Label: "plus de visites sérieuses", ctaText: "Demander une visite vidéo",
  },
  promotions: {
    sectionLabel: "Promotions immobilières",
    headline: "Les projets résidentiels",
    subtitle: "Découvrez les programmes immobiliers neufs commercialisés par Chabano Properties à Oran.",
  },
  testimonials: {
    sectionLabel: "Ils témoignent",
    headline: "Des résultats concrets,",
    subtitle: "Voici ce que disent les clients qui ont fait confiance à Chabano Properties.",
    testimonial1: { name: "Karim B.", role: "Acheteur — F3 Centre-Ville", text: "J'ai cherché pendant 6 mois sans rien trouver. Chabane m'a trouvé mon appartement en 3 semaines.", stars: 5, avatar: "K" },
    testimonial2: { name: "Samira O.", role: "Vendeuse — Bir El Djir", text: "Mon appartement était sur le marché depuis 4 mois. Après la vidéo de Chabane, j'ai reçu 3 offres en une semaine.", stars: 5, avatar: "S" },
    testimonial3: { name: "Mourad L.", role: "Investisseur", text: "Je travaille avec Chabane depuis 2 ans. Il connaît le marché mieux que personne.", stars: 5, avatar: "M" },
    result1: { value: "48h", label: "Délai moyen de premier contact" },
    result2: { value: "94%", label: "Taux de satisfaction client" },
    result3: { value: "3×", label: "Plus vite qu'une agence classique" },
    result4: { value: "100+", label: "Biens traités à Oran" },
  },
  finalCta: {
    label: "Prêt à agir ?",
    headline: "Votre bien à Oran",
    headlineGold: "vous attend déjà.",
    subtitle: "Chaque jour passé à hésiter, c'est une opportunité qui disparaît.",
    ctaPrimaryText: "Démarrer maintenant sur WhatsApp",
    ctaSecondaryText: "Appeler Chabane",
    availabilityText: "Réponse garantie en moins de 2 heures — Disponible 7j/7 de 9h à 21h",
  },
  footer: {
    brandName: "Chabano Properties",
    brandTagline: "Oran, Algérie",
    brandSubtitle: "Par Chabane Chawki — Agent Immobilier & Créateur de contenu",
    instagramUrl: "#", youtubeUrl: "#",
  },
  contact: {
    whatsappNumber: "213541029014",
    availabilityText: "Disponible du samedi au jeudi, de 9h à 21h.",
  },
}
